SRCS = CssBackground.java CssFontSize.java\
CssBackgroundAttachment.java CssFontStyle.java\
CssBackgroundColor.java CssFontVariant.java\
CssBackgroundConstants.java CssFontWeight.java\
CssBackgroundImage.java CssHeight.java\
CssBackgroundPosition.java CssLetterSpacing.java\
CssBackgroundRepeat.java CssLineHeight.java\
CssBorder.java CssListStyle.java\
CssBorderBottom.java CssListStyleConstants.java\
CssBorderBottomColor.java CssListStyleImage.java\
CssBorderBottomStyle.java CssListStylePosition.java\
CssBorderBottomWidth.java CssListStyleType.java\
CssBorderColor.java CssMargin.java\
CssMarginBottom.java\
CssBorderFaceColor.java CssMarginLeft.java\
CssBorderFaceStyle.java CssMarginRight.java\
CssBorderFaceWidth.java CssMarginSide.java\
CssBorderLeft.java CssMarginTop.java\
CssBorderLeftColor.java CssPadding.java\
CssBorderLeftStyle.java CssPaddingBottom.java\
CssBorderLeftWidth.java CssPaddingLeft.java\
CssBorderRight.java CssPaddingRight.java\
CssBorderRightColor.java CssPaddingSide.java\
CssBorderRightStyle.java CssPaddingTop.java\
CssBorderRightWidth.java\
CssBorderStyle.java CssProperties.java\
CssBorderStyleFace.java CssProperty.java\
CssBorderTop.java\
CssBorderTopColor.java Css1Style.java\
CssBorderTopStyle.java CssTextAlign.java\
CssBorderTopWidth.java CssTextDecoration.java\
CssBorderWidth.java CssTextIndent.java\
CssClear.java CssTextPropertiesConstants.java\
CssColor.java CssTextTransform.java\
CssDisplay.java CssVerticalAlign.java\
CssFloat.java CssWhiteSpace.java\
CssFont.java CssWidth.java\
CssFontConstant.java CssWordSpacing.java\
CssFontFamily.java

OBJS = $(SRCS:.java=.class)

PACKAGE = org.w3c.css.properties
JAVAC = javac
JAVADOC = javadoc
JAVADOCFLAGS = -version -d docs -protected
JAVACFLAGS =
MAKEDEPEND = jmakedepend

.SUFFIXES: .class .java
.java.class:; $(JAVAC) $(JAVACFLAGS) $<

all: $(OBJS)

javadoc:; $(JAVADOC) $(JAVADOCFLAGS) $(PACKAGE)

clean:; -rm -f $(OBJS) *~ core

depend:; $(MAKEDEPEND) $(SRCS)

# DO NOT DELETE THIS LINE -- make depend depends on it.
CssFloat.class:: CssFloat.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBorderLeftStyle.class:: CssBorderLeftStyle.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssTextPropertiesConstants.class:: CssTextPropertiesConstants.java
CssBorderRightStyle.class:: CssBorderRightStyle.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssMarginSide.class:: CssMarginSide.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssLength.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssPercentage.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssNumber.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBorderFaceColor.class:: CssBorderFaceColor.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssFontStyle.class:: CssFontStyle.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssListStyleImage.class:: CssListStyleImage.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssURL.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssFontFamily.class:: CssFontFamily.java\
	/usr/local/java11/bin/../lib/classes.zip\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/Util.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssOperator.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssString.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssVerticalAlign.class:: CssVerticalAlign.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssNumber.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssPercentage.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssColor.class:: CssColor.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBorderFaceStyle.class:: CssBorderFaceStyle.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBorderLeftWidth.class:: CssBorderLeftWidth.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssHeight.class:: CssHeight.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssLength.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssNumber.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssWordSpacing.class:: CssWordSpacing.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssLength.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssNumber.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssFontSize.class:: CssFontSize.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssPercentage.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssNumber.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssLength.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBorderBottom.class:: CssBorderBottom.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssPrinterStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssSelectors.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssOperator.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBorderLeft.class:: CssBorderLeft.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssPrinterStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssSelectors.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssOperator.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssPaddingBottom.class:: CssPaddingBottom.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBackgroundConstants.class:: CssBackgroundConstants.java
CssMargin.class:: CssMargin.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssSelectors.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssPrinterStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssOperator.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssListStyleType.class:: CssListStyleType.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBorderBottomColor.class:: CssBorderBottomColor.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssPrinterStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBorderFaceWidth.class:: CssBorderFaceWidth.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssLength.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssNumber.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssListStyle.class:: CssListStyle.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssPrinterStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssSelectors.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssOperator.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssProperty.class:: CssProperty.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssSelectors.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssPrinterStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.css/StyleSheetOrigin.class
CssTextDecoration.class:: CssTextDecoration.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBorderBottomStyle.class:: CssBorderBottomStyle.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssTextTransform.class:: CssTextTransform.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssFontWeight.class:: CssFontWeight.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssNumber.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssDisplay.class:: CssDisplay.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBorderTop.class:: CssBorderTop.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssSelectors.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssPrinterStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssOperator.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBorderStyle.class:: CssBorderStyle.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssPrinterStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssSelectors.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssOperator.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBorderRight.class:: CssBorderRight.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssPrinterStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssSelectors.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssOperator.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssMarginTop.class:: CssMarginTop.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBackground.class:: CssBackground.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssPrinterStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssSelectors.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssOperator.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssLetterSpacing.class:: CssLetterSpacing.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssLength.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssNumber.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBackgroundImage.class:: CssBackgroundImage.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssURL.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssFontConstant.class:: CssFontConstant.java
CssWhiteSpace.class:: CssWhiteSpace.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssMarginBottom.class:: CssMarginBottom.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssPadding.class:: CssPadding.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssSelectors.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssPrinterStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssOperator.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBorderStyleFace.class:: CssBorderStyleFace.java
CssBorderBottomWidth.class:: CssBorderBottomWidth.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBackgroundAttachment.class:: CssBackgroundAttachment.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBorderWidth.class:: CssBorderWidth.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssPrinterStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssSelectors.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssOperator.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssProperties.class:: CssProperties.java\
	/usr/local/java11/bin/../lib/classes.zip
CssTextIndent.class:: CssTextIndent.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssPercentage.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssLength.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssNumber.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBackgroundColor.class:: CssBackgroundColor.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssColor.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssClear.class:: CssClear.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssMarginRight.class:: CssMarginRight.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssPaddingLeft.class:: CssPaddingLeft.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssTextAlign.class:: CssTextAlign.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssListStylePosition.class:: CssListStylePosition.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBorderTopWidth.class:: CssBorderTopWidth.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBorderTopColor.class:: CssBorderTopColor.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssPrinterStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssPaddingRight.class:: CssPaddingRight.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssPaddingSide.class:: CssPaddingSide.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssLength.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssPercentage.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssNumber.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBorder.class:: CssBorder.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssPrinterStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssSelectors.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssFont.class:: CssFont.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssPrinterStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssSelectors.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssOperator.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBackgroundPosition.class:: CssBackgroundPosition.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssPercentage.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssLength.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssNumber.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssOperator.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssFontVariant.class:: CssFontVariant.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBorderColor.class:: CssBorderColor.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssPrinterStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssSelectors.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssOperator.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssListStyleConstants.class:: CssListStyleConstants.java
CssBorderRightWidth.class:: CssBorderRightWidth.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBorderRightColor.class:: CssBorderRightColor.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssPrinterStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
Css1Style.class:: Css1Style.java\
	/usr/local/java11/bin/../lib/classes.zip\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssSelectors.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssPrinterStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssPercentage.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssLength.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.css/StyleSheet.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/Warning.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/Warnings.class
CssBorderLeftColor.class:: CssBorderLeftColor.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssPrinterStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssPaddingTop.class:: CssPaddingTop.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBorderTopStyle.class:: CssBorderTopStyle.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssWidth.class:: CssWidth.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssNumber.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssLength.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssPercentage.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssMarginLeft.class:: CssMarginLeft.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssLineHeight.class:: CssLineHeight.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssNumber.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssLength.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssPercentage.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
CssBackgroundRepeat.class:: CssBackgroundRepeat.java\
	/u/koala/0/koala/plehegar/old/org.w3c.css.parser/CssStyle.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssExpression.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssValue.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.values/CssIdent.class\
	/u/koala/0/koala/plehegar/old/org.w3c.css.util/InvalidParamException.class
