css-validator:
    remote_url: https://github.com/w3c/css-validator.git
    remote_name: css-validator
    remote_branch: validator-nu
    last_local_merge: 4f0cdfcf77493774be85e76e1d8e1c0110a07e9b
    current_commit: f66e7ab509874b8940db4b7a00729813ce5146f2
htmlparser:
    remote_url: https://github.com/validator/htmlparser.git
    remote_name: htmlparser
    remote_branch: validator-nu
    last_local_merge: 01c08a29bbee79a86e0d8b3d27c49b41d4b41650
    current_commit: 0336b31c06307fc21e5d38166fb425b6d309196c
docs/wiki:
    remote_url: https://github.com/validator/validator.wiki.git
    remote_name: wiki
    remote_branch: master
    last_local_merge: 89416c41199641dbf395fe82bacfb5d1bb2d9072
    current_commit: ec4f15676733a38a888cba137f19a97f469395b7
galimatias:
    remote_url: https://github.com/validator/galimatias.git
    remote_name: galimatias
    remote_branch: master
    last_local_merge: 873373ef4508b9b75d54759218c6108107ad8df0
    current_commit: 8e893f3fe89baacd00d5f022e9b7ef0114d3372e
    skip_updates: true
jing-trang:
    remote_url: https://github.com/relaxng/jing-trang.git
    remote_name: jing-trang
    remote_branch: validator-nu
    last_local_merge: 9137d0342d04450fd6b0267b0d4ccbc3c50c4885
    current_commit: a2c48c075746d3f40d92ad66e3dd3dd69b10943f
    skip_updates: true
langdetect:
    remote_url: https://github.com/validator/language-detection.git
    remote_name: langdetect
    remote_branch: master
    last_local_merge: 5c324c54db1007a8edf4a4de448e28b5aedbd90e
    current_commit: 7a0bb1bfe30763d2bef71bbb8d8df693cfcd1f67
    skip_updates: true
tests:
    remote_url: https://github.com/validator/tests.git
    remote_name: tests
    remote_branch: master
    last_local_merge: 2f72907bcded18e025a9a346c3db6b68adf163f9
    current_commit: 11357f01eaad6199358a53a08fad58ac9162ea04
    skip_updates: true
