#!/bin/sh

# Copyright (c) 2006, Sun Microsystems, Inc.
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the Sun Microsystems, Inc. nor the names of its
#       contributors may be used to endorse or promote products derived from
#       this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
# THE POSSIBILITY OF SUCH DAMAGE.


install_name="javacc-$1"
export install_name
/bin/rm -rf dist
/bin/rm -f "${install_name}.tar.gz"
/bin/rm -f "${install_name}.zip"
mkdir -p "dist/${install_name}"
cp -rf scripts "dist/${install_name}/bin"
mkdir dist/$install_name/bin/lib
cp target/javacc.jar dist/$install_name/bin/lib/javacc.jar

chmod a+x "dist/${install_name}/bin/javacc"
chmod a+x "dist/${install_name}/bin/jjdoc"
chmod a+x "dist/${install_name}/bin/jjtree"
cp -rf www/doc "dist/${install_name}/doc"
cp -rf examples "dist/${install_name}/examples"
cp -rf LICENSE "dist/${install_name}"

cd dist
tar czf ./${install_name}.tar.gz $install_name
zip -qr ./${install_name}.zip $install_name
/bin/rm -rf dist
