language: java

addons:
  apt:
    packages:
      - openjdk-6-jdk

jdk:
  - openjdk6
  - openjdk7
  - openjdk8
  # https://github.com/travis-ci/travis-ci/issues/7884
  #- oraclejdk7
  - oraclejdk8

script:
  - ./ant test
