/* Generated By:JavaCC: Do not edit this line. CssParserConstants.java */
package org.w3c.css.parser.analyzer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CssParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 1;
  /** RegularExpression Id. */
  int H = 2;
  /** RegularExpression Id. */
  int NONASCII = 3;
  /** RegularExpression Id. */
  int UNICODE = 4;
  /** RegularExpression Id. */
  int ESCAPE = 5;
  /** RegularExpression Id. */
  int NMSTART = 6;
  /** RegularExpression Id. */
  int NMCHAR = 7;
  /** RegularExpression Id. */
  int STRING1 = 8;
  /** RegularExpression Id. */
  int STRING2 = 9;
  /** RegularExpression Id. */
  int INVALID1 = 10;
  /** RegularExpression Id. */
  int INVALID2 = 11;
  /** RegularExpression Id. */
  int _IDENT = 12;
  /** RegularExpression Id. */
  int NAME = 13;
  /** RegularExpression Id. */
  int NUM = 14;
  /** RegularExpression Id. */
  int _STRING = 15;
  /** RegularExpression Id. */
  int _INVALID = 16;
  /** RegularExpression Id. */
  int _URL = 17;
  /** RegularExpression Id. */
  int _S = 18;
  /** RegularExpression Id. */
  int _W = 19;
  /** RegularExpression Id. */
  int NL = 20;
  /** RegularExpression Id. */
  int S = 21;
  /** RegularExpression Id. */
  int SCO = 22;
  /** RegularExpression Id. */
  int CDO = 23;
  /** RegularExpression Id. */
  int CDC = 24;
  /** RegularExpression Id. */
  int INCLUDES = 25;
  /** RegularExpression Id. */
  int DASHMATCH = 26;
  /** RegularExpression Id. */
  int LBRACE = 27;
  /** RegularExpression Id. */
  int PLUS = 28;
  /** RegularExpression Id. */
  int MINUS = 29;
  /** RegularExpression Id. */
  int GREATER = 30;
  /** RegularExpression Id. */
  int GREATEREQ = 31;
  /** RegularExpression Id. */
  int COMMA = 32;
  /** RegularExpression Id. */
  int TILDE = 33;
  /** RegularExpression Id. */
  int TWOPIPES = 34;
  /** RegularExpression Id. */
  int AND = 35;
  /** RegularExpression Id. */
  int OR = 36;
  /** RegularExpression Id. */
  int ONLY = 37;
  /** RegularExpression Id. */
  int NOT = 38;
  /** RegularExpression Id. */
  int STRING = 39;
  /** RegularExpression Id. */
  int INVALID = 40;
  /** RegularExpression Id. */
  int IDENT = 41;
  /** RegularExpression Id. */
  int HASHIDENT = 42;
  /** RegularExpression Id. */
  int HASH = 43;
  /** RegularExpression Id. */
  int PROGID = 44;
  /** RegularExpression Id. */
  int CUSTOM_PROPERTY_NAME = 45;
  /** RegularExpression Id. */
  int RBRACE = 46;
  /** RegularExpression Id. */
  int PREFIXMATCH = 47;
  /** RegularExpression Id. */
  int SUFFIXMATCH = 48;
  /** RegularExpression Id. */
  int SUBSTRINGMATCH = 49;
  /** RegularExpression Id. */
  int EQ = 50;
  /** RegularExpression Id. */
  int SEMICOLON = 51;
  /** RegularExpression Id. */
  int DIV = 52;
  /** RegularExpression Id. */
  int LBRACKET = 53;
  /** RegularExpression Id. */
  int RBRACKET = 54;
  /** RegularExpression Id. */
  int ANY = 55;
  /** RegularExpression Id. */
  int DOT = 56;
  /** RegularExpression Id. */
  int RPAREN = 57;
  /** RegularExpression Id. */
  int LPAREN = 58;
  /** RegularExpression Id. */
  int COLON = 59;
  /** RegularExpression Id. */
  int URL = 60;
  /** RegularExpression Id. */
  int RELFONTLENGTH = 61;
  /** RegularExpression Id. */
  int RELVIEWLENGTH = 62;
  /** RegularExpression Id. */
  int ABSOLUTLENGTH = 63;
  /** RegularExpression Id. */
  int FLEX = 64;
  /** RegularExpression Id. */
  int ANGLE = 65;
  /** RegularExpression Id. */
  int SPL = 66;
  /** RegularExpression Id. */
  int ST = 67;
  /** RegularExpression Id. */
  int TIME = 68;
  /** RegularExpression Id. */
  int FREQ = 69;
  /** RegularExpression Id. */
  int RESOLUTION = 70;
  /** RegularExpression Id. */
  int AN = 71;
  /** RegularExpression Id. */
  int DIMEN_9 = 72;
  /** RegularExpression Id. */
  int DIMEN = 73;
  /** RegularExpression Id. */
  int PERCENTAGE = 74;
  /** RegularExpression Id. */
  int NUMBER = 75;
  /** RegularExpression Id. */
  int IMPORTANT_SYM = 76;
  /** RegularExpression Id. */
  int IMPORTANT_NOT = 77;
  /** RegularExpression Id. */
  int PSEUDOELEMENT_SYM = 78;
  /** RegularExpression Id. */
  int CHARSET_SYM = 79;
  /** RegularExpression Id. */
  int PAGE_SYM = 80;
  /** RegularExpression Id. */
  int PAGE_TOP_LEFT_CORNER = 81;
  /** RegularExpression Id. */
  int PAGE_TOP_LEFT = 82;
  /** RegularExpression Id. */
  int PAGE_TOP_CENTER = 83;
  /** RegularExpression Id. */
  int PAGE_TOP_RIGHT = 84;
  /** RegularExpression Id. */
  int PAGE_TOP_RIGHT_CORNER = 85;
  /** RegularExpression Id. */
  int PAGE_BOTTOM_LEFT_CORNER = 86;
  /** RegularExpression Id. */
  int PAGE_BOTTOM_LEFT = 87;
  /** RegularExpression Id. */
  int PAGE_BOTTOM_CENTER = 88;
  /** RegularExpression Id. */
  int PAGE_BOTTOM_RIGHT = 89;
  /** RegularExpression Id. */
  int PAGE_BOTTOM_RIGHT_CORNER = 90;
  /** RegularExpression Id. */
  int PAGE_LEFT_TOP = 91;
  /** RegularExpression Id. */
  int PAGE_LEFT_MIDDLE = 92;
  /** RegularExpression Id. */
  int PAGE_LEFT_BOTTOM = 93;
  /** RegularExpression Id. */
  int PAGE_RIGHT_TOP = 94;
  /** RegularExpression Id. */
  int PAGE_RIGHT_MIDDLE = 95;
  /** RegularExpression Id. */
  int PAGE_RIGHT_BOTTOM = 96;
  /** RegularExpression Id. */
  int IMPORT_SYM = 97;
  /** RegularExpression Id. */
  int NAMESPACE_SYM = 98;
  /** RegularExpression Id. */
  int MEDIA_SYM = 99;
  /** RegularExpression Id. */
  int FONT_FACE_SYM = 100;
  /** RegularExpression Id. */
  int KEYFRAMES_SYM = 101;
  /** RegularExpression Id. */
  int PREF_SYM = 102;
  /** RegularExpression Id. */
  int COLOR_PROFILE = 103;
  /** RegularExpression Id. */
  int A_COUNTER = 104;
  /** RegularExpression Id. */
  int COUNTER_STYLE_SYM = 105;
  /** RegularExpression Id. */
  int PHONETIC_ALPHABET_SYM = 106;
  /** RegularExpression Id. */
  int SUPPORTS_SYM = 107;
  /** RegularExpression Id. */
  int VIEWPORT_SYM = 108;
  /** RegularExpression Id. */
  int ATKEYWORD = 109;
  /** RegularExpression Id. */
  int RANGE0 = 110;
  /** RegularExpression Id. */
  int RANGE1 = 111;
  /** RegularExpression Id. */
  int RANGE2 = 112;
  /** RegularExpression Id. */
  int RANGE3 = 113;
  /** RegularExpression Id. */
  int RANGE4 = 114;
  /** RegularExpression Id. */
  int RANGE5 = 115;
  /** RegularExpression Id. */
  int RANGE6 = 116;
  /** RegularExpression Id. */
  int RANGE = 117;
  /** RegularExpression Id. */
  int UNI = 118;
  /** RegularExpression Id. */
  int UNICODERANGE = 119;
  /** RegularExpression Id. */
  int FUNCTIONLANG = 120;
  /** RegularExpression Id. */
  int FUNCTIONDIR = 121;
  /** RegularExpression Id. */
  int FUNCTIONIS = 122;
  /** RegularExpression Id. */
  int FUNCTIONWHERE = 123;
  /** RegularExpression Id. */
  int FUNCTIONHAS = 124;
  /** RegularExpression Id. */
  int FUNCTIONSLOTTED = 125;
  /** RegularExpression Id. */
  int FUNCTIONHOST = 126;
  /** RegularExpression Id. */
  int FUNCTIONHOSTCONTEXT = 127;
  /** RegularExpression Id. */
  int FUNCTIONNTHCHILD = 128;
  /** RegularExpression Id. */
  int FUNCTIONNTHLASTCHILD = 129;
  /** RegularExpression Id. */
  int FUNCTIONNTHCOL = 130;
  /** RegularExpression Id. */
  int FUNCTIONNTHLASTCOL = 131;
  /** RegularExpression Id. */
  int FUNCTIONNTHOFTYPE = 132;
  /** RegularExpression Id. */
  int FUNCTIONNTHLASTOFTYPE = 133;
  /** RegularExpression Id. */
  int FUNCTIONNOT = 134;
  /** RegularExpression Id. */
  int FUNCTIONCALC = 135;
  /** RegularExpression Id. */
  int FUNCTIONMATHN = 136;
  /** RegularExpression Id. */
  int FUNCTIONMATH1 = 137;
  /** RegularExpression Id. */
  int FUNCTIONMATH2 = 138;
  /** RegularExpression Id. */
  int FUNCTIONROUND = 139;
  /** RegularExpression Id. */
  int FUNCTIONCLAMP = 140;
  /** RegularExpression Id. */
  int FUNCTIONATTR = 141;
  /** RegularExpression Id. */
  int FUNCTIONVAR = 142;
  /** RegularExpression Id. */
  int FUNCTION = 143;
  /** RegularExpression Id. */
  int HTMLSTARTTAG = 144;
  /** RegularExpression Id. */
  int HTMLENDTAG = 145;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<COMMENT>",
    "<H>",
    "<NONASCII>",
    "<UNICODE>",
    "<ESCAPE>",
    "<NMSTART>",
    "<NMCHAR>",
    "<STRING1>",
    "<STRING2>",
    "<INVALID1>",
    "<INVALID2>",
    "<_IDENT>",
    "<NAME>",
    "<NUM>",
    "<_STRING>",
    "<_INVALID>",
    "<_URL>",
    "<_S>",
    "<_W>",
    "<NL>",
    "<S>",
    "\"/*\"",
    "\"<!--\"",
    "\"-->\"",
    "<INCLUDES>",
    "\"|=\"",
    "<LBRACE>",
    "<PLUS>",
    "\"-\"",
    "<GREATER>",
    "<GREATEREQ>",
    "<COMMA>",
    "<TILDE>",
    "<TWOPIPES>",
    "\"and\"",
    "\"or\"",
    "\"only\"",
    "\"not\"",
    "<STRING>",
    "<INVALID>",
    "<IDENT>",
    "<HASHIDENT>",
    "<HASH>",
    "<PROGID>",
    "<CUSTOM_PROPERTY_NAME>",
    "\"}\"",
    "\"^=\"",
    "\"$=\"",
    "\"*=\"",
    "\"=\"",
    "\";\"",
    "\"/\"",
    "\"[\"",
    "\"]\"",
    "\"*\"",
    "\".\"",
    "\")\"",
    "\"(\"",
    "\":\"",
    "<URL>",
    "<RELFONTLENGTH>",
    "<RELVIEWLENGTH>",
    "<ABSOLUTLENGTH>",
    "<FLEX>",
    "<ANGLE>",
    "<SPL>",
    "<ST>",
    "<TIME>",
    "<FREQ>",
    "<RESOLUTION>",
    "<AN>",
    "<DIMEN_9>",
    "<DIMEN>",
    "<PERCENTAGE>",
    "<NUMBER>",
    "<IMPORTANT_SYM>",
    "<IMPORTANT_NOT>",
    "\"::\"",
    "\"@charset\"",
    "\"@page\"",
    "\"@top-left-corner\"",
    "\"@top-left\"",
    "\"@top-center\"",
    "\"@top-right\"",
    "\"@top-right-corner\"",
    "\"@bottom-left-corner\"",
    "\"@bottom-left\"",
    "\"@bottom-center\"",
    "\"@bottom-right\"",
    "\"@bottom-right-corner\"",
    "\"@left-top\"",
    "\"@left-middle\"",
    "\"@left-bottom\"",
    "\"@right-top\"",
    "\"@right-middle\"",
    "\"@right-bottom\"",
    "\"@import\"",
    "\"@namespace\"",
    "\"@media\"",
    "\"@font-face\"",
    "\"@keyframes\"",
    "\"@preference\"",
    "\"@color-profile\"",
    "\"@counter\"",
    "\"@counter-style\"",
    "\"@phonetic-alphabet\"",
    "\"@supports\"",
    "\"@viewport\"",
    "<ATKEYWORD>",
    "<RANGE0>",
    "<RANGE1>",
    "<RANGE2>",
    "<RANGE3>",
    "<RANGE4>",
    "<RANGE5>",
    "<RANGE6>",
    "<RANGE>",
    "<UNI>",
    "<UNICODERANGE>",
    "\"lang(\"",
    "\"dir(\"",
    "\"is(\"",
    "\"where(\"",
    "\"has(\"",
    "\"slotted(\"",
    "\"host(\"",
    "\"host-context(\"",
    "\"nth-child(\"",
    "\"nth-last-child(\"",
    "\"nth-col(\"",
    "\"nth-last-col(\"",
    "\"nth-of-type(\"",
    "\"nth-last-of-type(\"",
    "\"not(\"",
    "<FUNCTIONCALC>",
    "<FUNCTIONMATHN>",
    "<FUNCTIONMATH1>",
    "<FUNCTIONMATH2>",
    "\"round(\"",
    "\"clamp(\"",
    "\"attr(\"",
    "\"var(\"",
    "<FUNCTION>",
    "<HTMLSTARTTAG>",
    "<HTMLENDTAG>",
    "\"!\"",
    "\"$\"",
    "\"%\"",
    "\"&\"",
    "\"`\"",
    "\"?\"",
    "\"<\"",
    "\"|\"",
    "\"<=\"",
  };

}
