name: "HTML conformance request"
description: "Request support for new or updated requirements in the HTML spec"
labels: [spec-conformance]
body:
  - type: markdown
    attributes:
      value: |
        To request support for new or updated requirements in the HTML spec, please provide both:
        - one or more URLs for the relevant spec sections or spec commits which specify the requirements
        - **an HTML snippet/document that can be used for testing checker support for the requirements**
        > [!IMPORTANT]
        > Providing a test case along with your request will help significantly in getting support for the spec requirements added to the checker.
  - type: input
    id: spec-url
    attributes:
      label: "Spec URL"
      description: "Provide one or more URLs to the relevant spec sections or spec commit."
      placeholder: https://html.spec.whatwg.org/multipage/… | https://github.com/whatwg/html/commit/…
    validations:
      required: true
  - type: textarea
    id: test-case
    attributes:
      label: "Test case"
      description: "Provide an HTML snippet for testing checker support for the spec requirements. (This will be formatted as a code block — so, no need to add code fences/backticks.)"
      render: html
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        &nbsp; <!-- add some vertical whitespace -->
        ## :heart: [Sponsor this project](https://github.com/sponsors/validator)

        The Nu Html Checker is **critical web infrastructure.** [Your sponsorship](https://github.com/sponsors/validator) helps keep continued work on it _sustainable_.
        &nbsp; <!-- add some vertical whitespace -->
# yaml-language-server: $schema=https://www.schemastore.org/github-issue-forms.json
