name: Bad Language Detection
description: Report an incorrectly detected language on a page
labels: [ "wrong-lang" ]
assignees: []
body:
  - type: input
    id: detected-language
    attributes:
      label: Detected language
      description: What was the language detected by vnu?
      placeholder: English
    validations:
      required: yes
  - type: input
    id: expected-language
    attributes:
      label: Expected language
      description: What language did you expect to be detected?
      placeholder: English
    validations:
      required: yes
  - type: checkboxes
    id: vnu-instance
    attributes:
      label: Instance of vnu
      description: What instance of vnu did you use?
      options:
        - label: https://validator.w3.org/nu/
        - label: vnu web interface (private instance)
        - label: Command line
        - label: vnu HTTP Client
    validations:
      required: true
  - type: input
    id: vnu-version
    attributes:
      label: Version of vnu
      description: |
        What is the version of vnu?
         - On the command line, run vnu with the `--version` option.
         - If you use the Web UI, the version is displayed on the result page.
      placeholder: 24.10.30
    validations:
      required: yes
  - type: checkboxes
    id: input-type
    attributes:
      label: Source type
      description: What was the type of your input?
      options:
        - label: Address or URL
        - label: File
        - label: Text input
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > In case of **Address or URL**, please attach also a copy of the file since the content at that URL may change, or become unavailable until this issue is processed.
  - type: textarea
    id: attached-file
    attributes:
      label: Attached file
      description: |
        Please drop or attach a copy of the file in the field below.
        You may use the `.txt` or `.html` extension.
    validations:
      required: no
  - type: input
    id: url
    attributes:
      label: Validated URL or Address
      description: The **URL** of the page, if you validate by address/URL.
      placeholder: https://www.example.com/page.html
    validations:
      required: no
  - type: textarea
    id: text-input
    attributes:
      label: Raw source / Text input
      description: If the source type is "Text input", copy the raw sources below as is (**without using markdown ticks**).
      placeholder: |
        <!DOCTYPE html>
        <html lang="cmn">
          <head>
            <meta charset="utf-8">
            <title>官话</title>
          </head>
          <body>
            <p>官话</p>
          </body>
        </html>
      render: html
    validations:
      required: no
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
    validations:
      required: no
