name: "Spec conformance request"
description: "Request validator support for a new or updated specification feature."
labels: [enhancement, spec-conformance]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "Describe the spec feature or change in 1 or 2 short sentences."
      placeholder: "The validator should support… from the… specification."
    validations:
      required: true
  - type: dropdown
    id: spec-type
    attributes:
      label: "Specification type"
      description: "Which specification is this request related to?"
      options:
        - HTML (WHATWG)
        - CSS
        - SVG
        - MathML
        - Accessibility (ARIA, etc.)
        - Other web standard
    validations:
      required: true
  - type: input
    id: spec-url
    attributes:
      label: "Specification URL"
      description: "Provide the URL to the relevant specification section or pull request."
      placeholder: https://html.spec.whatwg.org/multipage/…
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: "Feature description"
      description: "Provide a clear description of the specification feature or change."
    validations:
      required: true
  - type: textarea
    id: validation-behavior
    attributes:
      label: "Desired validation behavior"
      description: "Describe how the validator should handle this feature (e.g., what should be valid, what should produce errors or warnings)."
    validations:
      required: true
  - type: textarea
    id: example-code
    attributes:
      label: "Example code"
      description: "Provide example markup that demonstrates the feature. What you paste in will be formatted as a code block."
      render: html
    validations:
      required: false
  - type: dropdown
    id: status
    attributes:
      label: "Specification status"
      description: "What is the current status of this feature in the specification?"
      options:
        - Living Standard (stable)
        - Candidate Recommendation
        - Editor’s Draft (in development)
        - Proposed (PR or issue)
        - Other
    validations:
      required: true
  - type: textarea
    id: browser-support
    attributes:
      label: "Browser implementation status"
      description: "Optionally, provide information about which browsers have implemented this feature."
      placeholder: |
        - Chrome: Implemented in version X
        - Firefox: In development
        - Safari: Not yet implemented
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context"
      description: "Add any other relevant information, links, or context."
    validations:
      required: false
  - type: checkboxes
    id: will-implement
    attributes:
      label: "Contribute an implementation?"
      description: "If you plan to implement this feature yourself, please check the box below."
      options:
        - label: "I’ll contribute an implementation for this myself."
