/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int A = 1;
  /** RegularExpression Id. */
  int B = 2;
  /** RegularExpression Id. */
  int C = 3;
  /** RegularExpression Id. */
  int D = 4;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"A\"",
    "\"B\"",
    "\"C\"",
    "\"D\"",
  };

}
