all:
	perl -pi -e "s/<dt><a href=#element-dfn-tag-omission title=element-dfn-tag-omission>Tag omission in text\/html<\/a>:<\/dt>//" html5.html
	perl -pi -e "s/<dt><a href=#element-dfn-tag-omission title=element-dfn-tag-omission>Tag omission in text\/html<\/a>:<\/dt>//" w3c-html5.html
