name: Push a new Docker image
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Log in to the container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract tags and labels metadata
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ghcr.io/validator/validator
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/validator/validator:latest, ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
