/* This code was generated by nu.validator.tools.SaxCompiler. Please regenerate instead of editing. */
package nu.validator.servlet;
public final class CharsetEmitter {
private CharsetEmitter() {}
public static void emit(org.xml.sax.ContentHandler contentHandler, nu.validator.servlet.VerifierServletTransaction t) throws org.xml.sax.SAXException {
org.xml.sax.helpers.AttributesImpl __attrs__ = new org.xml.sax.helpers.AttributesImpl();
contentHandler.startPrefixMapping("", "http://www.w3.org/1999/xhtml");
__attrs__.clear();
__attrs__.addAttribute("", "title", "title", "CDATA", "Override for transfer protocol character encoding declaration.");
contentHandler.startElement("http://www.w3.org/1999/xhtml", "tr", "tr", __attrs__);
__attrs__.clear();
contentHandler.startElement("http://www.w3.org/1999/xhtml", "th", "th", __attrs__);
__attrs__.clear();
__attrs__.addAttribute("", "for", "for", "CDATA", "charset");
contentHandler.startElement("http://www.w3.org/1999/xhtml", "label", "label", __attrs__);
contentHandler.characters(__chars__, 0, 8);
contentHandler.endElement("http://www.w3.org/1999/xhtml", "label", "label");
contentHandler.endElement("http://www.w3.org/1999/xhtml", "th", "th");
__attrs__.clear();
contentHandler.startElement("http://www.w3.org/1999/xhtml", "td", "td", __attrs__);
__attrs__.clear();
__attrs__.addAttribute("", "id", "id", "CDATA", "charset");
__attrs__.addAttribute("", "name", "name", "CDATA", "charset");
contentHandler.startElement("http://www.w3.org/1999/xhtml", "select", "select", __attrs__);
__attrs__.clear();
__attrs__.addAttribute("", "value", "value", "CDATA", "");
contentHandler.startElement("http://www.w3.org/1999/xhtml", "option", "option", __attrs__);
contentHandler.characters(__chars__, 8, 25);
contentHandler.endElement("http://www.w3.org/1999/xhtml", "option", "option");
t.emitCharsetOptions(); 
		
contentHandler.endElement("http://www.w3.org/1999/xhtml", "select", "select");
contentHandler.endElement("http://www.w3.org/1999/xhtml", "td", "td");
contentHandler.endElement("http://www.w3.org/1999/xhtml", "tr", "tr");
contentHandler.endPrefixMapping("");
}
private static final char[] __chars__ = { 'E', 'n', 'c', 'o', 'd', 'i', 'n', 'g', 'A', 's', ' ', 's', 'e', 't', ' ', 'b', 'y', ' ', 't', 'h', 'e', ' ', 's', 'e', 'r', 'v', 'e', 'r', '/', 'p', 'a', 'g', 'e' };
}
