/* This code was generated by fi.iki.hsivonen.xml.SaxCompiler. Please regenerate instead of editing. */
package nu.validator.servlet;
public final class Html5FormEmitter {
private Html5FormEmitter() {}
public static void emit(org.xml.sax.ContentHandler contentHandler, nu.validator.servlet.VerifierServletTransaction t) throws org.xml.sax.SAXException {
org.xml.sax.helpers.AttributesImpl __attrs__ = new org.xml.sax.helpers.AttributesImpl();
contentHandler.startPrefixMapping("", "http://www.w3.org/1999/xhtml");
__attrs__.clear();
contentHandler.startElement("http://www.w3.org/1999/xhtml", "fieldset", "fieldset", __attrs__);
__attrs__.clear();
contentHandler.startElement("http://www.w3.org/1999/xhtml", "legend", "legend", __attrs__);
contentHandler.characters(__chars__, 0, 25);
contentHandler.endElement("http://www.w3.org/1999/xhtml", "legend", "legend");
__attrs__.clear();
contentHandler.startElement("http://www.w3.org/1999/xhtml", "table", "table", __attrs__);
__attrs__.clear();
contentHandler.startElement("http://www.w3.org/1999/xhtml", "tbody", "tbody", __attrs__);
__attrs__.clear();
__attrs__.addAttribute("", "title", "title", "CDATA", "IRI (http or https) of the document to be checked");
contentHandler.startElement("http://www.w3.org/1999/xhtml", "tr", "tr", __attrs__);
__attrs__.clear();
contentHandler.startElement("http://www.w3.org/1999/xhtml", "th", "th", __attrs__);
__attrs__.clear();
__attrs__.addAttribute("", "for", "for", "CDATA", "doc");
contentHandler.startElement("http://www.w3.org/1999/xhtml", "label", "label", __attrs__);
contentHandler.characters(__chars__, 25, 8);
contentHandler.endElement("http://www.w3.org/1999/xhtml", "label", "label");
contentHandler.endElement("http://www.w3.org/1999/xhtml", "th", "th");
__attrs__.clear();
contentHandler.startElement("http://www.w3.org/1999/xhtml", "td", "td", __attrs__);
t.emitDocField(); 
contentHandler.endElement("http://www.w3.org/1999/xhtml", "td", "td");
contentHandler.endElement("http://www.w3.org/1999/xhtml", "tr", "tr");
__attrs__.clear();
contentHandler.startElement("http://www.w3.org/1999/xhtml", "tr", "tr", __attrs__);
__attrs__.clear();
contentHandler.startElement("http://www.w3.org/1999/xhtml", "th", "th", __attrs__);
contentHandler.endElement("http://www.w3.org/1999/xhtml", "th", "th");
__attrs__.clear();
contentHandler.startElement("http://www.w3.org/1999/xhtml", "td", "td", __attrs__);
__attrs__.clear();
__attrs__.addAttribute("", "name", "name", "CDATA", "submit");
__attrs__.addAttribute("", "value", "value", "CDATA", "Check");
__attrs__.addAttribute("", "type", "type", "CDATA", "submit");
__attrs__.addAttribute("", "id", "id", "CDATA", "submit");
contentHandler.startElement("http://www.w3.org/1999/xhtml", "input", "input", __attrs__);
contentHandler.endElement("http://www.w3.org/1999/xhtml", "input", "input");
contentHandler.endElement("http://www.w3.org/1999/xhtml", "td", "td");
contentHandler.endElement("http://www.w3.org/1999/xhtml", "tr", "tr");
contentHandler.endElement("http://www.w3.org/1999/xhtml", "tbody", "tbody");
contentHandler.endElement("http://www.w3.org/1999/xhtml", "table", "table");
contentHandler.endElement("http://www.w3.org/1999/xhtml", "fieldset", "fieldset");
contentHandler.endPrefixMapping("");
}
private static final char[] __chars__ = { 'C', 'o', 'n', 'f', 'o', 'r', 'm', 'a', 'n', 'c', 'e', ' ', 'C', 'h', 'e', 'c', 'k', 'e', 'r', ' ', 'I', 'n', 'p', 'u', 't', 'D', 'o', 'c', 'u', 'm', 'e', 'n', 't' };
}
