/* This code was generated by nu.validator.tools.SaxCompiler. Please regenerate instead of editing. */
package nu.validator.servlet;
public final class NsFilterEmitter {
private NsFilterEmitter() {}
public static void emit(org.xml.sax.ContentHandler contentHandler, nu.validator.servlet.VerifierServletTransaction t) throws org.xml.sax.SAXException {
org.xml.sax.helpers.AttributesImpl __attrs__ = new org.xml.sax.helpers.AttributesImpl();
contentHandler.startPrefixMapping("", "http://www.w3.org/1999/xhtml");
__attrs__.clear();
__attrs__.addAttribute("", "title", "title", "CDATA", "Space-separated list of namespace URIs.");
contentHandler.startElement("http://www.w3.org/1999/xhtml", "tr", "tr", __attrs__);
__attrs__.clear();
contentHandler.startElement("http://www.w3.org/1999/xhtml", "th", "th", __attrs__);
__attrs__.clear();
__attrs__.addAttribute("", "for", "for", "CDATA", "nsfilter");
contentHandler.startElement("http://www.w3.org/1999/xhtml", "label", "label", __attrs__);
__attrs__.clear();
__attrs__.addAttribute("", "title", "title", "CDATA", "XML namespace");
contentHandler.startElement("http://www.w3.org/1999/xhtml", "abbr", "abbr", __attrs__);
contentHandler.characters(__chars__, 0, 5);
contentHandler.endElement("http://www.w3.org/1999/xhtml", "abbr", "abbr");
contentHandler.characters(__chars__, 5, 1);
contentHandler.characters(__chars__, 6, 6);
contentHandler.endElement("http://www.w3.org/1999/xhtml", "label", "label");
contentHandler.endElement("http://www.w3.org/1999/xhtml", "th", "th");
__attrs__.clear();
contentHandler.startElement("http://www.w3.org/1999/xhtml", "td", "td", __attrs__);
t.emitNsfilterField(); 
contentHandler.endElement("http://www.w3.org/1999/xhtml", "td", "td");
contentHandler.endElement("http://www.w3.org/1999/xhtml", "tr", "tr");
contentHandler.endPrefixMapping("");
}
private static final char[] __chars__ = { 'X', 'M', 'L', 'N', 'S', '\u00a0', 'F', 'i', 'l', 't', 'e', 'r' };
}
