/* This code was generated by nu.validator.tools.SaxCompiler. Please regenerate instead of editing. */
package nu.validator.servlet;
public final class PageEmitter {
private PageEmitter() {}
public static void emit(org.xml.sax.ContentHandler contentHandler, nu.validator.servlet.VerifierServletTransaction t) throws org.xml.sax.SAXException {
org.xml.sax.helpers.AttributesImpl __attrs__ = new org.xml.sax.helpers.AttributesImpl();
try {
contentHandler.startDocument();
contentHandler.startPrefixMapping("", "http://www.w3.org/1999/xhtml");
__attrs__.clear();
__attrs__.addAttribute("http://www.w3.org/XML/1998/namespace", "lang", "xml:lang", "CDATA", "en");
contentHandler.startElement("http://www.w3.org/1999/xhtml", "html", "html", __attrs__);
__attrs__.clear();
contentHandler.startElement("http://www.w3.org/1999/xhtml", "head", "head", __attrs__);
t.emitIcon(); 
t.emitStyle(); 
__attrs__.clear();
contentHandler.startElement("http://www.w3.org/1999/xhtml", "title", "title", __attrs__);
t.emitTitle(false); 
contentHandler.endElement("http://www.w3.org/1999/xhtml", "title", "title");
contentHandler.endElement("http://www.w3.org/1999/xhtml", "head", "head");
__attrs__.clear();
contentHandler.startElement("http://www.w3.org/1999/xhtml", "body", "body", __attrs__);
__attrs__.clear();
contentHandler.startElement("http://www.w3.org/1999/xhtml", "h1", "h1", __attrs__);
t.emitTitle(true); 
contentHandler.endElement("http://www.w3.org/1999/xhtml", "h1", "h1");
t.emitForm(); t.emitScript(); t.validate(); 
__attrs__.clear();
contentHandler.startElement("http://www.w3.org/1999/xhtml", "hr", "hr", __attrs__);
contentHandler.endElement("http://www.w3.org/1999/xhtml", "hr", "hr");
__attrs__.clear();
contentHandler.startElement("http://www.w3.org/1999/xhtml", "p", "p", __attrs__);
t.emitAbout(); 
contentHandler.endElement("http://www.w3.org/1999/xhtml", "p", "p");
contentHandler.endElement("http://www.w3.org/1999/xhtml", "body", "body");
contentHandler.endElement("http://www.w3.org/1999/xhtml", "html", "html");
contentHandler.endPrefixMapping("");
} finally {
contentHandler.endDocument();
}
}
private static final char[] __chars__ = { };
}
