/* This code was generated by nu.validator.tools.SaxCompiler. Please regenerate instead of editing. */
package nu.validator.servlet;
public final class StatsEmitter {
private StatsEmitter() {}
public static void emit(org.xml.sax.ContentHandler contentHandler, nu.validator.servlet.VerifierServletTransaction t) throws org.xml.sax.SAXException {
org.xml.sax.helpers.AttributesImpl __attrs__ = new org.xml.sax.helpers.AttributesImpl();
contentHandler.startPrefixMapping("", "http://www.w3.org/1999/xhtml");
__attrs__.clear();
__attrs__.addAttribute("", "class", "class", "CDATA", "stats");
contentHandler.startElement("http://www.w3.org/1999/xhtml", "p", "p", __attrs__);
contentHandler.characters(__chars__, 0, 21);
t.emitTotalDuration(); 
contentHandler.characters(__chars__, 21, 14);
contentHandler.endElement("http://www.w3.org/1999/xhtml", "p", "p");
contentHandler.endPrefixMapping("");
}
private static final char[] __chars__ = { 'T', 'o', 't', 'a', 'l', ' ', 'e', 'x', 'e', 'c', 'u', 't', 'i', 'o', 'n', ' ', 't', 'i', 'm', 'e', ' ', ' ', 'm', 'i', 'l', 'l', 'i', 's', 'e', 'c', 'o', 'n', 'd', 's', '.' };
}
