name: CI Build

on:
  pull_request:
  push:
    branches: [main]

jobs:
  darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Update submodules
        run: python ./checker.py update
      - name: Install dependencies
        run: python ./checker.py dldeps
      - name: Build
        uses: ./.github/actions/build

  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - 16
          - 11
          - 8
          - 17-ea
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Update submodules
        run: python ./checker.py update
      - name: Install dependencies
        run: python ./checker.py dldeps
      - name: Build
        uses: ./.github/actions/build

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Update submodules
        run: python .\checker.py update
      - name: Install dependencies
        run: python .\checker.py dldeps
      - name: Build
        run: |
          python .\checker.py build
          python .\checker.py jar
          python .\checker.py image
          python .\checker.py war
          java -jar .\build\dist\vnu.jar .\build\dist\index.html
          java -jar .\build\dist\vnu.jar .\site\nu-about.html
          python .\checker.py check
          python .\checker.py test
