name: macOS build for vnu

on:
  push:
    branches: [main]
  pull_request:

jobs:
  darwin:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Update submodules
        run: python ./checker.py update
      - name: Install dependencies
        run: python ./checker.py dldeps
      - name: Build
        uses: ./.github/actions/build
      - name: Import GPG signing key
        uses: crazy-max/ghaction-import-gpg@v3
        if: github.ref == 'refs/heads/main'
        with:
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          passphrase: ${{ secrets.GPG_SIGNING_KEY_PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true
      - name: Sign release artifacts
        if: github.ref == 'refs/heads/main'
        run: |
          for file in build/dist/{*.zip,*.zip.md5,*.zip.sha1}; do gpg --yes -ab --sign $file; done || true
          for file in build/dist/*.jar*; do gpg --yes -ab --sign $file; done || true
          for file in build/dist-war/*.war*; do gpg --yes -ab --sign $file; done || true
      - name: Release new macOS binary image
        uses: ncipollo/release-action@v1.8.6
        if: github.ref == 'refs/heads/main'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.sha }}
          allowUpdates: true
          artifacts: build/dist/*.zip*
          body: ${{ github.sha }} — ${{ github.event.head_commit.message }}
          name: latest
          omitName: true
          prerelease: true
          tag: latest
